config/routes.rb
Rails.application.routes.draw do
  resources :backing_tracks
  get "recordings/new/:title/:part" => "recordings#new", as: 'new_rec'
  get 'mixes/new/(:title)/(:part)', to: 'mixes#new'
  resources :recordings
  resources :mixes
  devise_for :users
  get 'dashboard' => 'main#dashboard'
  root "main#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recording.rb
class Recording < ApplicationRecord
  belongs_to :user
  has_one_attached :rec_file
  has_and_belongs_to_many :mixes
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  before_action :set_recording, only: [:show, :edit, :update, :destroy]

  # GET /recordings
  # GET /recordings.json
  def index
    @recordings = Recording.all
    @backing_tracks = BackingTrack.all.group("song_title")
  end

  # GET /recordings/1
  # GET /recordings/1.json
  def show
  end

  # GET /recordings/new
  def new
    @backing_tracks = BackingTrack.all.group("song_title")
    @recording = Recording.new
    @track = BackingTrack.where("song_title = ? AND song_part = ?", params[:title], params[:part]).first
  end
  
  # GET /recordings/1/edit
  def edit
  end

  # POST /recordings
  # POST /recordings.json
  def create
    @recording = Recording.new(recording_params)
    @recording.user = current_user
    respond_to do |format|
      if @recording.save
        format.html { redirect_to @recording, notice: 'Recording was successfully created.' }
        format.json { render :show, status: :created, location: @recording }
      else
        format.html { render :new }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recordings/1
  # PATCH/PUT /recordings/1.json
  def update
    respond_to do |format|
      if @recording.update(recording_params)
        format.html { redirect_to @recording, notice: 'Recording was successfully updated.' }
        format.json { render :show, status: :ok, location: @recording }
      else
        format.html { render :edit }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recordings/1
  # DELETE /recordings/1.json
  def destroy
    @recording.destroy
    respond_to do |format|
      format.html { redirect_to recordings_url, notice: 'Recording was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recording
      @recording = Recording.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recording_params
      params.require(:recording).permit(:user_id, :part, :title, :rec_file)
    end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/recordings/_form.html.erb
<div data-controller="recording">
  <%= form_with(model: recording, multipart: true, local: true) do |form| %>
  <% if recording.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(recording.errors.count, "error") %> prohibited this recording from being saved:</h2>

    <ul>
      <% recording.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p data-target="recording.user"><%= current_user.email %> </p>

  <h2 data-target="recording.title"><%= params[:title] %></h2>

  <h2 data-target="recording.part"><%= params[:part] %></h2>

  <audio hidden="true" controls data-target="recording.backingTrack">
    <source src="<%= url_for @track.track %>" type="audio/mp3">
  </audio>

  <audio controls data-target="recording.activeTrack">
  </audio><br>

  <audio controls data-target="recording.saved">
  </audio>

  <div data-action="click->recording#start">Start</div><Br>
  <div data-action="click->recording#stop">Stop</div>
  <a href="" data-target="recording.recFile">Download</a>

  <%= form.label :rec_file %>

  <%= form.hidden_field :part, :value => params[:part]%>
  <%= form.hidden_field :title, :value => params[:title]%>


  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>

</div>

app/views/recordings/edit.html.erb
<h1>Editing Recording</h1>

<%= render 'form', recording: @recording %>

<%= link_to 'Show', @recording %> |
<%= link_to 'Back', recordings_path %>

app/views/recordings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recordings</h1>

<table>
  <thead>
    <tr>
      <th>Recorded By</th>
      <th>Part</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recordings.each do |recording| %>
    <tr>
      <td><%= recording.user.email %></td>
      <td><%= recording.part %></td>
      <td><%= recording.title %></td>
      <td><%= link_to 'Show', recording %></td>
      <td><%= link_to 'Edit', edit_recording_path(recording) %></td>
      <td><%= link_to 'Destroy', recording, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div data-controller="song">

  <%= select(:part, "part", %w[Soprano Alto Tenor Bass], {}, {data: {target: "song.part"}}) %>
  <%= select_tag :title, options_for_select(@backing_tracks.map{ |track| [track.song_title] }), prompt: 'select', data: {target: "song.title", action: "click->song#defineParams"} %>
  <a href="#" data-target="song.link">Go</a>
</div>

app/views/recordings/new.html.erb
<h1>New Recording</h1>

<%= render 'form', recording: @recording %>

<%= link_to 'Back', recordings_path %>

app/views/recordings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @recording.user.email %>
</p>

<p>
  <strong>Part:</strong>
  <%= @recording.part %>
</p>

<p>
  <% @path = rails_blob_path(@recording.rec_file) %>
  <audio controls>
    <source src="<%= @path %>" type="audio/mp3">
    Your browser does not support the audio tag.
  </audio>
</p>

<p>
  <strong>Title:</strong>
  <%=link_to url_for(@recording.rec_file) do %> <%= @recording.title %> <% end %>
</p>

<p>The blob file is - <%= @recording.rec_file %></p>

<%= link_to 'Edit', edit_recording_path(@recording) %> |
<%= link_to 'Back', recordings_path %>