config/routes.rb
Rails.application.routes.draw do
  resources :backing_tracks
  get "recordings/new/:title/:part" => "recordings#new", as: 'new_rec'
  get 'mixes/new/(:title)/(:part)', to: 'mixes#new'
  resources :recordings
  resources :mixes
  devise_for :users
  get 'dashboard' => 'main#dashboard'
  root "main#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/mix.rb
class Mix < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :recordings
  has_one_attached :mixed_file
end

app/controllers/mixes_controller.rb
class MixesController < ApplicationController
  before_action :set_mix, only: [:show, :edit, :update, :destroy]

  # GET /mixes
  # GET /mixes.json
  def index
    @mixes = Mix.all
    @recordings = Recording.all.group("title")
  end

  # GET /mixes/1
  # GET /mixes/1.json
  def show
  end

  # GET /mixes/new
  def new
    @mix = Mix.new
    if params[:title]
    @recordings = Recording.where(:title => params[:title]).where(:part => params[:part])
    else
      @recordings = Recording.all
    end
  end

  # GET /mixes/1/edit
  def edit
  end

  # POST /mixes
  # POST /mixes.json
  def create
    @mix = Mix.new(mix_params)
    
    respond_to do |format|
      if @mix.save


        @recordings = @mix.recordings
        @username = current_user.username
        @random = rand(9000..10000)
        @recordings.each do |r|
          f = r.rec_file
          f.open do |fl|
            cmd1 = `mkdir -pv temp/mixing/#{@username}`
            cmd2 = `opusdec --force-wav #{fl.path} - | sox - temp/mixing/#{@username}/#{@username}-#{r.title}-#{r.part}.mp3`
          puts fl.path
          puts cmd1, cmd2
          end
        end 
        cmd3 = `pwd && cd temp/mixing/#{@username} && pwd && sox -m * #{@username}-#{@random}.mp3`
        puts cmd3
        @mix.mixed_file.attach(io: File.open(Dir.pwd + "/temp/mixing/#{@username}/#{@username}-#{@random}.mp3"), filename: "#{@username}-#{@random}.mp3")
        cmd4 = `pwd && rm -r temp/mixing/#{@username}`
        puts "The final directory path is - " + cmd4

        format.html { redirect_to @mix, notice: 'Mix was successfully created.' }
        format.json { render :show, status: :created, location: @mix }
      else
        format.html { render :new }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mixes/1
  # PATCH/PUT /mixes/1.json
  def update
    respond_to do |format|
      if @mix.update(mix_params)
        format.html { redirect_to @mix, notice: 'Mix was successfully updated.' }
        format.json { render :show, status: :ok, location: @mix }
      else
        format.html { render :edit }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mixes/1
  # DELETE /mixes/1.json
  def destroy
    @mix.destroy
    respond_to do |format|
      format.html { redirect_to mixes_url, notice: 'Mix was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mix
      @mix = Mix.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mix_params
      params.require(:mix).permit(:user_id, recording_ids: [])
    end
end

app/helpers/mixes_helper.rb
module MixesHelper
end

app/views/mixes/_form.html.erb
<%= form_with(model: mix, local: true) do |form| %>
<% if mix.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(mix.errors.count, "error") %> prohibited this mix from being saved:</h2>

  <ul>
    <% mix.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :user_id %>
  <%= form.text_field :user_id %>
</div>
<div class="field">
  <%= form.label :recording_ids %>
  <%= form.select(:recording_ids, @recordings.collect {|r| [ "#{r.title} #{r.part} - #{r.user.email}", r.id ] }, 
  { :prompt => "Please select"}, 
  { :multiple => true, :size => 5 }) %>
</div>


<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/mixes/edit.html.erb
<h1>Editing Mix</h1>

<%= render 'form', mix: @mix %>

<%= link_to 'Show', @mix %> |
<%= link_to 'Back', mixes_path %>

app/views/mixes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mixes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mixes.each do |mix| %>
    <tr>
      <td><%= mix.user_id %></td>
      <td><%= link_to 'Show', mix %></td>
      <td><%= link_to 'Edit', edit_mix_path(mix) %></td>
      <td><%= link_to 'Destroy', mix, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<div data-controller="recording-filter">

  <%= select(:part, "part", %w[Soprano Alto Tenor Bass], {}, {data: {target: "recording-filter.part"}}) %>
  <%= select_tag :title, options_for_select(@recordings.map{ |rec| [rec.title] }), prompt: 'select', data: {target: "recording-filter.title", action: "click->recording-filter#defineParams"} %>
  <a href="#" data-target="recording-filter.link">Go</a>
</div>

app/views/mixes/new.html.erb
<h1>New Mix</h1>

<%= render 'form', mix: @mix %>

<%= link_to 'Back', mixes_path %>

app/views/mixes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @mix.user_id %>
</p>

<p>
  <% @path = rails_blob_path(@mix.mixed_file) %>
  <audio controls>
    <source src="<%= @path %>" type="audio/mp3">
    Your browser does not support the audio tag.
  </audio>
</p>

<%= link_to 'Edit', edit_mix_path(@mix) %> |
<%= link_to 'Back', mixes_path %>