config/routes.rb
Rails.application.routes.draw do
  resources :backing_tracks
  get "recordings/new/:title/:part" => "recordings#new", as: 'new_rec'
  get 'mixes/new/(:title)/(:part)', to: 'mixes#new'
  resources :recordings
  resources :mixes
  devise_for :users
  get 'dashboard' => 'main#dashboard'
  root "main#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/backing_track.rb
class BackingTrack < ApplicationRecord
  belongs_to :user
  has_one_attached :track
end

app/controllers/backing_tracks_controller.rb
class BackingTracksController < ApplicationController
  before_action :set_backing_track, only: [:show, :edit, :update, :destroy]

  # GET /backing_tracks
  # GET /backing_tracks.json
  def index
    @backing_tracks = BackingTrack.all
  end

  # GET /backing_tracks/1
  # GET /backing_tracks/1.json
  def show
  end

  # GET /backing_tracks/new
  def new
    @backing_track = BackingTrack.new
  end

  # GET /backing_tracks/1/edit
  def edit
  end

  # POST /backing_tracks
  # POST /backing_tracks.json
  def create
    @backing_track = BackingTrack.new(backing_track_params)
    @backing_track.user_id = current_user.id
    respond_to do |format|
      if @backing_track.save
        format.html { redirect_to @backing_track, notice: 'Backing track was successfully created.' }
        format.json { render :show, status: :created, location: @backing_track }
      else
        format.html { render :new }
        format.json { render json: @backing_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backing_tracks/1
  # PATCH/PUT /backing_tracks/1.json
  def update
    respond_to do |format|
      if @backing_track.update(backing_track_params)
        format.html { redirect_to @backing_track, notice: 'Backing track was successfully updated.' }
        format.json { render :show, status: :ok, location: @backing_track }
      else
        format.html { render :edit }
        format.json { render json: @backing_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backing_tracks/1
  # DELETE /backing_tracks/1.json
  def destroy
    @backing_track.destroy
    respond_to do |format|
      format.html { redirect_to backing_tracks_url, notice: 'Backing track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backing_track
      @backing_track = BackingTrack.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def backing_track_params
      params.require(:backing_track).permit(:song_title, :song_part, :track)
    end
end

app/helpers/backing_tracks_helper.rb
module BackingTracksHelper
end

app/views/backing_tracks/_form.html.erb
<%= form_with(model: backing_track, local: true) do |form| %>
<% if backing_track.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(backing_track.errors.count, "error") %> prohibited this backing_track from being saved:</h2>

  <ul>
    <% backing_track.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :song_title %>
  <%= form.text_field :song_title %>
</div>

<div class="field">
  <%= form.label :song_part %>
  <%= form.text_field :song_part %>
</div>

<div class="field">
  <%= form.label :track %>
  <%= form.file_field :track %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/backing_tracks/edit.html.erb
<h1>Editing Backing Track</h1>

<%= render 'form', backing_track: @backing_track %>

<%= link_to 'Show', @backing_track %> |
<%= link_to 'Back', backing_tracks_path %>

app/views/backing_tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Backing Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Song title</th>
      <th>Song part</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @backing_tracks.each do |backing_track| %>
    <tr>
      <td><%= backing_track.song_title %></td>
      <td><%= backing_track.song_part %></td>
      <td><%= link_to 'Show', backing_track %></td>
      <td><%= link_to 'Edit', edit_backing_track_path(backing_track) %></td>
      <td><%= link_to 'Destroy', backing_track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Backing Track', new_backing_track_path %>

app/views/backing_tracks/new.html.erb
<h1>New Backing Track</h1>

<%= render 'form', backing_track: @backing_track %>

<%= link_to 'Back', backing_tracks_path %>

app/views/backing_tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Song title:</strong>
  <%= @backing_track.song_title %>
</p>

<p>
  <strong>Song part:</strong>
  <%= @backing_track.song_part %>
</p>

<p>
  <% @path = rails_blob_path(@backing_track.track) %>
  <audio controls>
    <source src="<%= @path %>" type="audio/mp3">
    Your browser does not support the audio tag.
  </audio>
</p>

<p>
  <strong>Uploaded By:</strong>
  <%= @backing_track.user.email %>
</p>

<%= link_to 'Edit', edit_backing_track_path(@backing_track) %> |
<%= link_to 'Back', backing_tracks_path %>